import Header from "@/components/Header"
import "./globals.css"
import type { Metadata } from "next"
import { Gabarito } from "next/font/google"
import Nav from "@/components/Nav"

const gabarito = Gabarito({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-gabarito",
  display: "swap",
  preload: true,
  fallback: ["sans-serif"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={gabarito.className}>
        <Header />
        <Nav />
        {children}
      </body>
    </html>
  )
}
